### ISSUE TITLE
[bug] CrashLoopBackOff when index.ts #L30 gatewayAPI: true

### ISSUE THREAD

**Issue by usrbinkat** [usrbinkat/cilium-kubernetes#1]
# Problem:

Setting helm chart cilium/cilium value `gatewayAPI: true` causes cilium-operator pod crash loop.

# How To Reproduce:

1. Follow README.md codespaces kind and pulumi deploy setup.
2. Set [index.ts#L30](https://github.com/usrbinkat/iac-mesh-pac/blob/main/index.ts#L30) `ciliumHelmValues["gatewayAPI"]` value to true
3. re-run `pulumi up` to deploy changes
4. delete cilium-operator-* pod and monitor logs of it's replacement.

# Result

```bash
iac-mesh-pac on <> main [!] via <> v20.11.0 via <> usrbinkat@iac-mesh-pac 
🐋❯ kubectl -n kube-system logs cilium-operator-6986d77db4-8ql9q | grep -v info
level=fatal msg="Failed to create gateway controller" error="failed to get API group resources: unable to retrieve the complete list of server APIs: gateway.networking.k8s.io/v1beta1: the server could not find the requested resource" subsys=gateway-controller
```

**Comment by distributethe6ix** [comment]
So, there's a known issue where enabling GatewayAPI and another function isn't currently support. Let me review the Helm yaml for a second.

**Comment by distributethe6ix** [comment]
Found the issue. Per the docs on Kube-proxy replacement: strict:
`Cilium’s eBPF kube-proxy replacement does not allow hostPort port configurations for Pods that overlap with the configured NodePort range. In such case, the hostPort setting will be ignored and a warning emitted to the Cilium agent log. Similarly, explicitly binding the hostIP to the loopback address in the host namespace is currently not supported and will log a warning to the Cilium agent log`
